### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by strarsis** [ItinerisLtd/trellis-backup-during-deploy#11]
Last commit/change to master was on 8 June, last release (0.1.2) was on 22 May.

Also update the README afterwards. 👍

**Comment by tangrufus** [comment]
Only changes is the `src`on readme:

```diff
 # requirements.yml
-- src: git+https://github.com/ItinerisLtd/trellis-backup-during-deploy.git
+- src: https://github.com/ItinerisLtd/trellis-backup-during-deploy
   version: 0.1.2 # Check for latest version!
```

Both `src` work (one uses SSH, one uses HTTP api). We will wait for some actual code changes before tagging a new release.

Thanks for using this project! Hope it saves you when bad things happen!

See: https://github.com/ItinerisLtd/trellis-backup-during-deploy/compare/0.1.2...b19442d
